import { sql, type ColumnDefinitionBuilder, type Kysely } from "kysely";
import type { Migration } from "kysely/migration";

const uuid = (column: ColumnDefinitionBuilder) => column.primaryKey().defaultTo(sql`gen_random_uuid()`);
const created = (column: ColumnDefinitionBuilder) => column.notNull().defaultTo(sql`now()`);

export const libraryIndexingMigration: Migration = {
  async up(db: Kysely<unknown>) {
    await db.schema.createTable("books").addColumn("id", "uuid", uuid).addColumn("title", "text", c => c.notNull()).addColumn("status", "text", c => c.notNull().defaultTo("active")).addColumn("created_by", "uuid", c => c.notNull()).addColumn("created_at", "timestamptz", created).addColumn("updated_at", "timestamptz", created).addForeignKeyConstraint("books_created_by_fk", ["created_by"], "users", ["id"]).addCheckConstraint("books_status_check", sql`status in ('active','archived')`).execute();
    await db.schema.createIndex("books_overview_idx").on("books").columns(["status", "created_at", "id"]).execute();
    await db.schema.createTable("book_sources").addColumn("id", "uuid", uuid).addColumn("book_id", "uuid", c => c.notNull()).addColumn("provider", "text", c => c.notNull()).addColumn("source_id", "text", c => c.notNull()).addColumn("start_chapter", "integer", c => c.notNull()).addColumn("end_chapter", "integer", c => c.notNull()).addColumn("created_at", "timestamptz", created).addColumn("updated_at", "timestamptz", created).addForeignKeyConstraint("book_sources_book_id_fk", ["book_id"], "books", ["id"], c => c.onDelete("cascade")).addUniqueConstraint("book_sources_book_id_unique", ["book_id"]).addCheckConstraint("book_sources_range_check", sql`start_chapter > 0 and end_chapter >= start_chapter`).execute();
    await db.schema.createTable("chapters").addColumn("id", "uuid", uuid).addColumn("book_id", "uuid", c => c.notNull()).addColumn("chapter_index", "integer", c => c.notNull()).addColumn("title", "text", c => c.notNull()).addColumn("content_hmac", "text", c => c.notNull()).addColumn("content_ciphertext", "bytea", c => c.notNull()).addColumn("content_nonce", "bytea", c => c.notNull()).addColumn("content_tag", "bytea", c => c.notNull()).addColumn("content_key_version", "text", c => c.notNull()).addColumn("source_version", "text", c => c.notNull()).addColumn("created_at", "timestamptz", created).addColumn("updated_at", "timestamptz", created).addForeignKeyConstraint("chapters_book_id_fk", ["book_id"], "books", ["id"], c => c.onDelete("cascade")).addUniqueConstraint("chapters_book_id_chapter_index_unique", ["book_id", "chapter_index"]).addUniqueConstraint("chapters_id_book_id_unique", ["id", "book_id"]).addCheckConstraint("chapters_chapter_index_check", sql`chapter_index > 0`).execute();
    await db.schema.createIndex("chapters_book_range_idx").on("chapters").columns(["book_id", "chapter_index"]).execute();
    await db.schema.createTable("prompt_versions").addColumn("id", "uuid", uuid).addColumn("target", "text", c => c.notNull()).addColumn("version", "text", c => c.notNull()).addColumn("content_hash", "text", c => c.notNull()).addColumn("created_at", "timestamptz", created).addUniqueConstraint("prompt_versions_target_version_unique", ["target", "version"]).addCheckConstraint("prompt_versions_target_check", sql`target in ('l1-index','l2-index')`).execute();
    await db.schema.createTable("workflow_versions").addColumn("id", "uuid", uuid).addColumn("target", "text", c => c.notNull()).addColumn("contract_version", "text", c => c.notNull()).addColumn("dsl_hash", "text", c => c.notNull()).addColumn("enabled", "boolean", c => c.notNull().defaultTo(true)).addColumn("created_at", "timestamptz", created).addUniqueConstraint("workflow_versions_target_contract_dsl_unique", ["target", "contract_version", "dsl_hash"]).addCheckConstraint("workflow_versions_target_check", sql`target in ('chapter-import','l1-index','l2-index')`).execute();
    await db.schema.createTable("index_groups").addColumn("id", "uuid", uuid).addColumn("book_id", "uuid", c => c.notNull()).addColumn("key", "text", c => c.notNull()).addColumn("name", "text", c => c.notNull()).addColumn("prompt_version_id", "uuid", c => c.notNull()).addColumn("config_hash", "text", c => c.notNull()).addColumn("status", "text", c => c.notNull().defaultTo("active")).addColumn("created_at", "timestamptz", created).addForeignKeyConstraint("index_groups_book_id_fk", ["book_id"], "books", ["id"], c => c.onDelete("cascade")).addForeignKeyConstraint("index_groups_prompt_version_id_fk", ["prompt_version_id"], "prompt_versions", ["id"]).addUniqueConstraint("index_groups_book_id_key_unique", ["book_id", "key"]).addUniqueConstraint("index_groups_id_book_id_unique", ["id", "book_id"]).addCheckConstraint("index_groups_status_check", sql`status in ('active','archived')`).execute();
    await db.schema.createTable("l1_indexes").addColumn("id", "uuid", uuid).addColumn("chapter_id", "uuid", c => c.notNull()).addColumn("prompt_version_id", "uuid", c => c.notNull()).addColumn("workflow_version_id", "uuid", c => c.notNull()).addColumn("input_signature", "text", c => c.notNull()).addColumn("status", "text", c => c.notNull()).addColumn("is_current", "boolean", c => c.notNull().defaultTo(true)).addColumn("route", "jsonb", c => c.notNull()).addColumn("created_at", "timestamptz", created).addForeignKeyConstraint("l1_indexes_chapter_id_fk", ["chapter_id"], "chapters", ["id"], c => c.onDelete("cascade")).addForeignKeyConstraint("l1_indexes_prompt_version_id_fk", ["prompt_version_id"], "prompt_versions", ["id"]).addForeignKeyConstraint("l1_indexes_workflow_version_id_fk", ["workflow_version_id"], "workflow_versions", ["id"]).addCheckConstraint("l1_indexes_status_check", sql`status in ('fresh','failed','stale')`).execute();
    await sql`create unique index l1_indexes_current_chapter_unique on l1_indexes (chapter_id) where is_current`.execute(db);
    await db.schema.createIndex("l1_indexes_coverage_idx").on("l1_indexes").columns(["chapter_id", "status"]).execute();
    await db.schema.createTable("l2_chapter_statuses").addColumn("id", "uuid", uuid).addColumn("group_id", "uuid", c => c.notNull()).addColumn("chapter_id", "uuid", c => c.notNull()).addColumn("book_id", "uuid", c => c.notNull()).addColumn("input_signature", "text", c => c.notNull()).addColumn("status", "text", c => c.notNull()).addColumn("failure_code", "text").addColumn("updated_at", "timestamptz", created).addForeignKeyConstraint("l2_chapter_statuses_group_book_fk", ["group_id", "book_id"], "index_groups", ["id", "book_id"], c => c.onDelete("cascade")).addForeignKeyConstraint("l2_chapter_statuses_chapter_book_fk", ["chapter_id", "book_id"], "chapters", ["id", "book_id"], c => c.onDelete("cascade")).addUniqueConstraint("l2_chapter_statuses_group_chapter_unique", ["group_id", "chapter_id"]).addCheckConstraint("l2_chapter_statuses_status_check", sql`status in ('fresh','failed','stale')`).execute();
    await db.schema.createIndex("l2_group_coverage_idx").on("l2_chapter_statuses").columns(["group_id", "status", "chapter_id"]).execute();
    await db.schema.createTable("l2_subjects").addColumn("id", "uuid", uuid).addColumn("group_id", "uuid", c => c.notNull()).addColumn("subject_key", "text", c => c.notNull()).addColumn("display_name", "text", c => c.notNull()).addColumn("aliases", "jsonb", c => c.notNull().defaultTo(sql`'[]'::jsonb`)).addColumn("created_at", "timestamptz", created).addForeignKeyConstraint("l2_subjects_group_id_fk", ["group_id"], "index_groups", ["id"], c => c.onDelete("cascade")).addUniqueConstraint("l2_subjects_group_subject_unique", ["group_id", "subject_key"]).execute();
    await db.schema.createTable("l2_facts").addColumn("id", "uuid", uuid).addColumn("group_id", "uuid", c => c.notNull()).addColumn("chapter_id", "uuid", c => c.notNull()).addColumn("book_id", "uuid", c => c.notNull()).addColumn("subject_key", "text", c => c.notNull()).addColumn("fact_type", "text", c => c.notNull()).addColumn("fact_ciphertext", "bytea", c => c.notNull()).addColumn("fact_nonce", "bytea", c => c.notNull()).addColumn("fact_tag", "bytea", c => c.notNull()).addColumn("fact_key_version", "text", c => c.notNull()).addColumn("metadata", "jsonb", c => c.notNull()).addColumn("created_at", "timestamptz", created).addForeignKeyConstraint("l2_facts_group_book_fk", ["group_id", "book_id"], "index_groups", ["id", "book_id"], c => c.onDelete("cascade")).addForeignKeyConstraint("l2_facts_chapter_book_fk", ["chapter_id", "book_id"], "chapters", ["id", "book_id"], c => c.onDelete("cascade")).addForeignKeyConstraint("l2_facts_group_subject_fk", ["group_id", "subject_key"], "l2_subjects", ["group_id", "subject_key"]).execute();
    await db.schema.createIndex("l2_fact_review_idx").on("l2_facts").columns(["group_id", "id"]).execute();
  },
  async down(db: Kysely<unknown>) {
    for (const table of ["l2_facts", "l2_subjects", "l2_chapter_statuses", "l1_indexes", "index_groups", "workflow_versions", "prompt_versions", "chapters", "book_sources", "books"]) await db.schema.dropTable(table).execute();
  },
};
